baseurl = "http://www.ivandx.com"
title = "Ivan Deschenaux"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Ivan Deschenaux"
  info = "Cognitive Anthropologist and Research Methods Enthusiast"
  description = "Ivan Deschenaux's personal website."
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

# customCSS = ["css/custom.css"]
# customSCSS = ["scss/custom.scss"]
# customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/idhx/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/IvDhx/"

# Menu links
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
