baseURL : "http://ivandx.com/"
languageCode : "en-us"
title : "Ivan Deschenaux"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  defaultTheme: auto
  disableThemeToggle: true
  title : "Ivan Deschenaux"
  description : "Ivan Deschenaux - Cognitive Anthropologist and Research Methods Enthusiast"
  keywords: [Ivan, Deschenaux, personal, anthropology, anthropologist, methodology, methodologist, research methods]

  profileMode:
    enabled: true
    title: "Ivan Deschenaux" # optional default will be site title
    subtitle: "Cognitive Anthropologist and Research Methods Enthusiast"
    imageUrl: "images/ivan.jpg" # optional
    imageTitle: "Ivan Deschenaux" # optional
    imageWidth: 300 # custom size
    imageHeight: 300 # custom size
    buttons:
      - name: Contact me
        url: "contact/"

  socialIcons:
    - name: email
      url: "mailto:i.deschenaux@lse.ac.uk"
    - name: linkedin
      url: "https://www.linkedin.com/in/ivandeschenaux/"
    - name: github
      url: "https://github.com/idhx"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=m0MhHMkAAAAJ"
    - name: orcid
      url: "https://orcid.org/0000-0002-7737-6255"

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favico/favicon.ico"
    favicon16x16:  "/favico/favicon-16x16.png"
    favicon32x32:  "/favico/favicon-32x32.png"
    apple_touch_icon:  "/favico/apple-touch-icon.png"
    # safari_pinned_tab:  "/favico/safari-pinned-tab.svg"

menu:
  main:
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 20
